# Generated by Django 2.2.6 on 2019-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreoperation', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('annee_de_livraison', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('mandataire', models.CharField(max_length=200)),
                ('ppi', models.CharField(max_length=200)),
                ('lycee', models.CharField(max_length=200)),
                ('notification_du_marche', models.DateField(blank=True, null=True)),
                ('codeuai', models.CharField(max_length=200)),
                ('longitude', models.FloatField(default=0.0)),
                ('etat_d_avancement', models.CharField(max_length=200)),
                ('montant_des_ap_votes_en_meu', models.IntegerField(default=0)),
                ('cao_attribution', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('maitrise_d_oeuvre', models.CharField(max_length=200)),
                ('mode_de_devolution', models.CharField(max_length=200)),
                ('annee_d_individualisation', models.IntegerField(default=0)),
                ('enveloppe_prev_en_meu', models.FloatField(default=0.0)),
            ],
        ),
    ]
